const ApplicationStatus = {
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  AWAITING_OXXO_PAYMENT: 'AWAITING_OXXO_PAYMENT',
  PAYMENT_PROCESSING: 'PAYMENT_PROCESSING',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',

  GENERATING_PERMIT: 'GENERATING_PERMIT',
  ERROR_GENERATING_PERMIT: 'ERROR_GENERATING_PERMIT',
  PERMIT_READY: 'PERMIT_READY',

  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',

  RENEWAL_PENDING: 'RENEWAL_PENDING',
  RENEWAL_APPROVED: 'RENEWAL_APPROVED',
  RENEWAL_REJECTED: 'RENEWAL_REJECTED'
};

const PaymentStatus = {
  PENDING: 'PENDING',
};

const DocumentType = {
  PERMIT: 'PERMIT',
  RECEIPT: 'RECEIPT',
};

const DEFAULT_PERMIT_FEE = 197.00;

module.exports = {
  ...ApplicationStatus,
  ApplicationStatus,
  PaymentStatus,
  DocumentType,
  DEFAULT_PERMIT_FEE
};
